### ISSUE TITLE
Collapse elements do not work

### ISSUE THREAD

**Issue by ziyaddin** [mrholek/CoreUI-Angular#11]
There are two problems regarding Collapse elements (http://coreui.io/docs/components/collapse/):
1. Anchor tag is routing to another page called `#collapseOne` due to href attribute:
```<a data-toggle="collapse" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">```
2. JavaScript function provided in the docs (```$('.collapse').collapse()```) does not work. Instead, it gives an error like that:
`Property 'collapse' does not exist on type 'JQuery<HTMLElement>'.`

**Comment by mrholek** [comment]
We don't use jQuery in Angular version. Please try this solution: https://valor-software.com/ngx-bootstrap/#/collapse

**Comment by ziyaddin** [comment]
Thanks for clarification and docs!
