### ISSUE TITLE
bug RTL version 

### ISSUE THREAD

**Issue by h4mit** [mrholek/CoreUI-Angular#19]
Hi, when use RTL version template navbar It does not function well. responsive method when of change to tablet or mobilephone state It does not function like picture.
![ip6](https://user-images.githubusercontent.com/4971751/31651454-93461830-b328-11e7-9f70-782905603375.PNG)

**Comment by h4mit** [comment]
fixed the problem, add "sidebar" class to "core/_rtl.scss" file for change left to right.

**Comment by taraman** [comment]
can u please send the change and the place of it

**Comment by IdanDavidi** [comment]
@h4mit can you post the change?
