### ISSUE TITLE
The text in some of the buttons is black (#111)

### ISSUE THREAD

**Issue by dushkostanoeski** [mrholek/CoreUI-Angular#2]
I'm using bootstrap 4 beta and I'm importing it from node_modules. 

The text inside a primary, success and danger button is white, but for the others it is #111.

**Comment by mrholek** [comment]
Bootstrap 4 uses this function to set text color inside buttons and badges:

`// Color contrast
@mixin color-yiq($color) {
  $r: red($color);
  $g: green($color);
  $b: blue($color);

  $yiq: (($r * 299) + ($g * 587) + ($b * 114)) / 1000;

  @if ($yiq >= 150) {
    color: #111;
  } @else {
    color: #fff;
  }
}`
