### ISSUE TITLE
No interaction possible after opening a modal

### ISSUE THREAD

**Issue by aakashjain** [mrholek/CoreUI-Angular#3]
It is no longer possible to click anything on the page once a modal is opened. You can only dismiss it by pressing Escape. This seems to be the case with all current versions of CoreUI, not just Angular. Even the [documentation page for modals](http://coreui.io/docs/components/modal/) has this problem. Click the "Launch demo modal" button on the above page and try to click anything.

The issue is with this recent addition to the theme's core/_temp.scss:
```{sass}
.modal-open .modal {
  display: block;
}
```

Not sure why this was even added, but this causes **all** modals defined on the page to have `display: block;` when any one modal is open. This means only the last modal defined on the page would be interactive.

Temporary workaround - add the following to your _custom.css:
```{sass}
// Fix for error in CoreUI
.modal-open {
  .modal {
    display: none !important;
  }
  .modal.show {
    display: block !important;
  }
}
```

**Comment by mrholek** [comment]
We will fix it next release

**Comment by mrholek** [comment]
Fixed in latest version
