### ISSUE TITLE
How to use bootstrap alerts?

### ISSUE THREAD

**Issue by kamal0808** [mrholek/CoreUI-Angular#36]
Your current documentation shows how to use bootstrap alerts with Jquery only. How can they be used in Angular2+?

**Comment by hozjanmarko** [comment]
Do it the angular way... Make a component for a modal
import { Component, ViewChild, Input, TemplateRef } from '@angular/core';
import { BsModalService, BsModalRef } from 'ngx-bootstrap/modal';
 
@Component({
  selector: 'ngx-modal',
  templateUrl: './ngx-modal.component.html',
  styleUrls: ['./ngx-modal.component.scss']
})
export class NgxModalComponent {
  @ViewChild('modal')
  protected modal: TemplateRef<any>;
  public Title: string;
  public Content: string;
 
  protected Visible: Boolean = false;
 
  protected Show(options: ngxModalOption, modalClass: string): BsModalRef {
    this.Title = options.Title;
    this.Content = options.Content;
 
    this.Visible = true;
    this.modalRef = this.modalService.show(this.modal, { class: modalClass });
    return this.modalRef;
  }
 
  @Input()
  public ShowWarning(options: ngxModalOption): BsModalRef {
    return this.Show(options, "modal-dialog modal-lg modal-warning");
  }
 
  @Input()
  public ShowSucess(options: ngxModalOption): BsModalRef {
    return this.Show(options, "modal-dialog modal-lg modal-success");
  }
 
  @Input()
  public ShowDaneger(options: ngxModalOption): BsModalRef {
    return this.Show(options, "modal-dialog modal-lg modal-danger");
  }
 
  @Input()
  public ShowInfo(options: ngxModalOption): BsModalRef {
    return this.Show(options, "modal-dialog modal-lg modal-info");
  }
 
  @Input()
  public ShowPrimary(options: ngxModalOption): BsModalRef {
    return this.Show(options, "modal-dialog modal-lg modal-primary");
  }
 
  @Input()
  public Close() {
    if (this.Visible)
      this.modalRef.hide();
  }
 
  modalRef: BsModalRef;
 
  constructor(private modalService: BsModalService) { }
}
 
export interface ngxModalOption {
  Title: string;
  Content: string;
}
<ng-template #modal>
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title">{{Title}}</h4>
      <button type="button" class="close" (click)="modalRef.hide()" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <div class="modal-body">
      <p>{{Content}}</p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" (click)="modalRef.hide()">close</button>
    </div>
  </div>
</ng-template>

**Comment by hozjanmarko** [comment]
I was writimg this on a phone :p

**Comment by kamal0808** [comment]
@hozjanmarko Is this code gonna generate modals or notification alerts?

**Comment by hozjanmarko** [comment]
Modals... If are looking for a notification service, you could use ng2-toasty, dont forget to add the css of the package to the styles sectio of angular cli json

**Comment by kamal0808** [comment]
Thanks, I'm going with https://github.com/scttcper/ngx-toastr.
