### ISSUE TITLE
Please really update Angular5_CLI_Full_Project

### ISSUE THREAD

**Issue by alvipeo** [mrholek/CoreUI-Angular#55]
If one now grabs this project and compiles it looks different from what you have here - http://coreui.io/demo/Angular2_Demo/#/dashboard . This is important.

**Comment by AndrewLien** [comment]
The compiled version of the full sample project isn't supposed to look like the **Angular 2** demo.

They even mention on their website it's supposed to look like this: http://coreui.io/demo/Angular_Demo/#/dashboard 

Which is similar to what I just compiled now. I also used their previous commits for another project that *had* the demo you listed above and I guess they upgraded to a new look for 2018.

**Comment by alvipeo** [comment]
So? Why not update it? Take the navbar for example - it has mail icon with badge and the avatar has dropdown triangle.

Well, I don't know...

**Comment by xidedix** [comment]
Angular2_Demo has been removed as obsolete
