### ISSUE TITLE
Live preview link not working/outdated

### ISSUE THREAD

**Issue by Fabioluxx** [mrholek/CoreUI-Angular#60]
URL: https://coreui.io/demo/Angular2_Demo
Giving me error 404

**Comment by xidedix** [comment]
Angular2_Demo has been removed as obsolete.
Please use [https://coreui.io/demo/Angular_Demo/](https://coreui.io/demo/Angular_Demo/) instead.

**Comment by Fabioluxx** [comment]
Thanks!
But the link here is outdated: https://coreui.io/angular/

**Comment by xidedix** [comment]
Thanks for the heads up @Fabioluxx !

**Comment by xidedix** [comment]
fixed

**Comment by AdemirSJRP** [comment]
When will Core UI Pro be updated with these last changes?
