### ISSUE TITLE
: Property 'chartHovered' does not exist on type componenet

### ISSUE THREAD

**Issue by BMLande** [mrholek/CoreUI-Angular#63]
hello ,
i found following error when i build tempate in production mode, with
ng build --prod

ERROR in src\app\dashboard\finance\finance.component.html(14,11): : Property 'chartHovered' does not exist on type 'FinanceComponent'.

thanks

**Comment by BMLande** [comment]
need to define charts function in component.ts ..thanks

**Comment by David-Lio** [comment]
Just add this to your component.ts

  public chartClicked(e:any):void {
    console.log(e);
  }
 
  public chartHovered(e:any):void {
    console.log(e);
  }
