### ISSUE TITLE
How to enable rtl?

### ISSUE THREAD

**Issue by MOstafaMRady** [mrholek/CoreUI-Angular#8]

**Comment by mrholek** [comment]
Add `dir="rtl"` to html tag. `<html dir="rtl">`

**Comment by MOstafaMRady** [comment]
![image](https://user-images.githubusercontent.com/5473932/30007631-cc7cc95a-9113-11e7-82bf-896d53f897b5.png)
RTL direction is not rendering as should be on mobile view

**Comment by MoAsmar** [comment]
> Add `dir="rtl"` to html tag. `<html dir="rtl">`

This only changes direction of the dom elements, sass mixins are not applied on margins and paddings
